// <auto-generated />
using System;
using CarService.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarService.Infrastructure.Migrations
{
    [DbContext(typeof(AutoServiceDbContext))]
    [Migration("20260501185630_SeedInitialData")]
    partial class SeedInitialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CarService.Infrastructure.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id")
                        .HasName("PK__Clients__3214EC07AC7A3FBB");

                    b.HasIndex(new[] { "Phone" }, "IX_Clients_Phone");

                    b.HasIndex(new[] { "Phone" }, "UQ__Clients__5C7E359E70B1BB43")
                        .IsUnique();

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("CarService.Infrastructure.Manufacturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Manufact__3214EC071D778699");

                    b.ToTable("Manufacturers");
                });

            modelBuilder.Entity("CarService.Infrastructure.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("Mileage")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<decimal?>("TotalAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m);

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Orders__3214EC07E0B4A786");

                    b.HasIndex(new[] { "StatusId" }, "IX_Orders_StatusId");

                    b.HasIndex(new[] { "VehicleId" }, "IX_Orders_VehicleId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("CarService.Infrastructure.OrderPart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int?>("PartId")
                        .HasColumnType("int");

                    b.Property<string>("PartName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18, 3)");

                    b.HasKey("Id")
                        .HasName("PK__OrderPar__3214EC07C098ACCE");

                    b.HasIndex("OrderId");

                    b.HasIndex("PartId");

                    b.ToTable("OrderParts");
                });

            modelBuilder.Entity("CarService.Infrastructure.OrderService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CustomName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(1m);

                    b.Property<int?>("ServiceId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__OrderSer__3214EC0734E06C52");

                    b.HasIndex("OrderId");

                    b.HasIndex("ServiceId");

                    b.ToTable("OrderServices");
                });

            modelBuilder.Entity("CarService.Infrastructure.Part", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("ManufacturerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("PurchasePrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 3)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("SellingPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Sku")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("SKU");

                    b.HasKey("Id")
                        .HasName("PK__Parts__3214EC077ADF4A09");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ManufacturerId");

                    b.HasIndex(new[] { "Sku" }, "IX_Parts_SKU");

                    b.ToTable("Parts");
                });

            modelBuilder.Entity("CarService.Infrastructure.PartCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__PartCate__3214EC07E3051CFC");

                    b.ToTable("PartCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Фільтри та оливи"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Гальмівна система"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Підвіска та рульове"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Освітлення та електрика"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Кузовні елементи"
                        });
                });

            modelBuilder.Entity("CarService.Infrastructure.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Roles__3214EC07BEA2A7C0");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Менеджер"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Майстер"
                        });
                });

            modelBuilder.Entity("CarService.Infrastructure.Schedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime");

                    b.Property<int>("MechanicId")
                        .HasColumnType("int");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime");

                    b.HasKey("Id")
                        .HasName("PK__Schedule__3214EC07B3DD7579");

                    b.HasIndex("MechanicId");

                    b.HasIndex("OrderId");

                    b.HasIndex("PostId");

                    b.HasIndex(new[] { "StartTime" }, "IX_Schedules_StartTime");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("CarService.Infrastructure.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<decimal>("DefaultPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id")
                        .HasName("PK__Services__3214EC070BCEFC9B");

                    b.HasIndex("CategoryId");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("CarService.Infrastructure.ServiceCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__ServiceC__3214EC071D4358DF");

                    b.ToTable("ServiceCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Технічне обслуговування"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Ходова частина"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Двигун та трансмісія"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Електрообладнання"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Діагностика"
                        });
                });

            modelBuilder.Entity("CarService.Infrastructure.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Statuses__3214EC0702506FB9");

                    b.ToTable("Statuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Новий"
                        },
                        new
                        {
                            Id = 2,
                            Name = "В роботі"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Очікує запчастини"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Готово"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Закрито"
                        });
                });

            modelBuilder.Entity("CarService.Infrastructure.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Users__3214EC07C0296B1B");

                    b.HasIndex("RoleId");

                    b.HasIndex(new[] { "Login" }, "UQ__Users__5E55825B516C6AA6")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CarService.Infrastructure.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("ModelId")
                        .HasColumnType("int");

                    b.Property<string>("Vin")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("nvarchar(17)")
                        .HasColumnName("VIN");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Vehicles__3214EC07A81ADF6E");

                    b.HasIndex("ClientId");

                    b.HasIndex("ModelId");

                    b.HasIndex(new[] { "LicensePlate" }, "IX_Vehicles_LicensePlate");

                    b.HasIndex(new[] { "Vin" }, "IX_Vehicles_VIN");

                    b.HasIndex(new[] { "Vin" }, "UQ__Vehicles__C5DF234CD73C8193")
                        .IsUnique();

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("CarService.Infrastructure.VehicleBrand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__VehicleB__3214EC07D673CE6F");

                    b.HasIndex(new[] { "Name" }, "UQ__VehicleB__737584F6D01BAC2D")
                        .IsUnique();

                    b.ToTable("VehicleBrands");
                });

            modelBuilder.Entity("CarService.Infrastructure.VehicleModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__VehicleM__3214EC0705D79F11");

                    b.HasIndex("BrandId");

                    b.ToTable("VehicleModels");
                });

            modelBuilder.Entity("CarService.Infrastructure.WorkPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__WorkPost__3214EC07F9E9C3FD");

                    b.ToTable("WorkPosts");
                });

            modelBuilder.Entity("CarService.Infrastructure.Order", b =>
                {
                    b.HasOne("CarService.Infrastructure.Status", "Status")
                        .WithMany("Orders")
                        .HasForeignKey("StatusId")
                        .IsRequired()
                        .HasConstraintName("FK_Orders_Statuses");

                    b.HasOne("CarService.Infrastructure.Vehicle", "Vehicle")
                        .WithMany("Orders")
                        .HasForeignKey("VehicleId")
                        .IsRequired()
                        .HasConstraintName("FK_Orders_Vehicles");

                    b.Navigation("Status");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("CarService.Infrastructure.OrderPart", b =>
                {
                    b.HasOne("CarService.Infrastructure.Order", "Order")
                        .WithMany("OrderParts")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_OrderParts_Orders");

                    b.HasOne("CarService.Infrastructure.Part", "Part")
                        .WithMany("OrderParts")
                        .HasForeignKey("PartId")
                        .HasConstraintName("FK_OrderParts_Parts");

                    b.Navigation("Order");

                    b.Navigation("Part");
                });

            modelBuilder.Entity("CarService.Infrastructure.OrderService", b =>
                {
                    b.HasOne("CarService.Infrastructure.Order", "Order")
                        .WithMany("OrderServices")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_OrderServices_Orders");

                    b.HasOne("CarService.Infrastructure.Service", "Service")
                        .WithMany("OrderServices")
                        .HasForeignKey("ServiceId")
                        .HasConstraintName("FK_OrderServices_Services");

                    b.Navigation("Order");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("CarService.Infrastructure.Part", b =>
                {
                    b.HasOne("CarService.Infrastructure.PartCategory", "Category")
                        .WithMany("Parts")
                        .HasForeignKey("CategoryId")
                        .IsRequired()
                        .HasConstraintName("FK_Parts_Categories");

                    b.HasOne("CarService.Infrastructure.Manufacturer", "Manufacturer")
                        .WithMany("Parts")
                        .HasForeignKey("ManufacturerId")
                        .IsRequired()
                        .HasConstraintName("FK_Parts_Manufacturers");

                    b.Navigation("Category");

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("CarService.Infrastructure.Schedule", b =>
                {
                    b.HasOne("CarService.Infrastructure.User", "Mechanic")
                        .WithMany("Schedules")
                        .HasForeignKey("MechanicId")
                        .IsRequired()
                        .HasConstraintName("FK_Schedules_Users");

                    b.HasOne("CarService.Infrastructure.Order", "Order")
                        .WithMany("Schedules")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Schedules_Orders");

                    b.HasOne("CarService.Infrastructure.WorkPost", "Post")
                        .WithMany("Schedules")
                        .HasForeignKey("PostId")
                        .IsRequired()
                        .HasConstraintName("FK_Schedules_WorkPosts");

                    b.Navigation("Mechanic");

                    b.Navigation("Order");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("CarService.Infrastructure.Service", b =>
                {
                    b.HasOne("CarService.Infrastructure.ServiceCategory", "Category")
                        .WithMany("Services")
                        .HasForeignKey("CategoryId")
                        .IsRequired()
                        .HasConstraintName("FK_Services_Categories");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("CarService.Infrastructure.User", b =>
                {
                    b.HasOne("CarService.Infrastructure.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK_Users_Roles");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("CarService.Infrastructure.Vehicle", b =>
                {
                    b.HasOne("CarService.Infrastructure.Client", "Client")
                        .WithMany("Vehicles")
                        .HasForeignKey("ClientId")
                        .HasConstraintName("FK_Vehicles_Clients");

                    b.HasOne("CarService.Infrastructure.VehicleModel", "Model")
                        .WithMany("Vehicles")
                        .HasForeignKey("ModelId")
                        .IsRequired()
                        .HasConstraintName("FK_Vehicles_Models");

                    b.Navigation("Client");

                    b.Navigation("Model");
                });

            modelBuilder.Entity("CarService.Infrastructure.VehicleModel", b =>
                {
                    b.HasOne("CarService.Infrastructure.VehicleBrand", "Brand")
                        .WithMany("VehicleModels")
                        .HasForeignKey("BrandId")
                        .IsRequired()
                        .HasConstraintName("FK_VehicleModels_Brands");

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("CarService.Infrastructure.Client", b =>
                {
                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("CarService.Infrastructure.Manufacturer", b =>
                {
                    b.Navigation("Parts");
                });

            modelBuilder.Entity("CarService.Infrastructure.Order", b =>
                {
                    b.Navigation("OrderParts");

                    b.Navigation("OrderServices");

                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("CarService.Infrastructure.Part", b =>
                {
                    b.Navigation("OrderParts");
                });

            modelBuilder.Entity("CarService.Infrastructure.PartCategory", b =>
                {
                    b.Navigation("Parts");
                });

            modelBuilder.Entity("CarService.Infrastructure.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("CarService.Infrastructure.Service", b =>
                {
                    b.Navigation("OrderServices");
                });

            modelBuilder.Entity("CarService.Infrastructure.ServiceCategory", b =>
                {
                    b.Navigation("Services");
                });

            modelBuilder.Entity("CarService.Infrastructure.Status", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("CarService.Infrastructure.User", b =>
                {
                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("CarService.Infrastructure.Vehicle", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("CarService.Infrastructure.VehicleBrand", b =>
                {
                    b.Navigation("VehicleModels");
                });

            modelBuilder.Entity("CarService.Infrastructure.VehicleModel", b =>
                {
                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("CarService.Infrastructure.WorkPost", b =>
                {
                    b.Navigation("Schedules");
                });
#pragma warning restore 612, 618
        }
    }
}
